version: "3.7"

services:
    webapp:
        container_name: webapp
        build:
            context: ${APP_ROOT}
            dockerfile: infra/docker/Dockerfile
            target: build
        deploy:
        env_file:
            - "${APP_ROOT}/infra/config/.env"
        ports:
            - 3400:3000
        user: "root"
        volumes:
            - "${APP_ROOT}:/app"
        networks:
            - hub2_network
        entrypoint: /bin/sh -c "npm install && npm run start"


networks:
    hub2_network:
        external: true
        name: hub2_network
