const HEADERS = "";
const USERNAME ="";
const PASSWORD="";
const URL="";
const TOKEN="";
const BASEURLTRANSFERCHECKPROVIDERSTATUS="";
const BASEURLTRANSFERCHECKHUB2STATUS ="";
const BASETRANSFERURLSOLDE="";
const BASEURLTRANSFERREFRESHSTATUS="";

const APPKEY = "b1413ec5-e76c-4c38-8a1f-38a7a67e0f7c";

const ENVIRONMENT = {
    LIVE:"live"
};